// apps/playground/src/samples/Button.sample.tsx
import type { ReactNode } from "react";
import { button } from "virtual:styleframe";

interface ButtonProps {
	color?:
		| "primary"
		| "secondary"
		| "success"
		| "info"
		| "warning"
		| "error"
		| "light"
		| "dark"
		| "neutral";
	variant?: "solid" | "outline" | "soft" | "subtle" | "ghost" | "link";
	size?: "xs" | "sm" | "md" | "lg" | "xl";
	disabled?: boolean;
	children?: ReactNode;
}

export default function Button({
	color = "primary",
	variant = "solid",
	size = "md",
	disabled,
	children,
}: ButtonProps) {
	// `neutral` is the recipe default, so only set color for the others.
	return (
		<button
			type="button"
			className={button({
				variant,
				size,
				...(color !== "neutral" && { color }),
			})}
			disabled={disabled}
		>
			{children}
		</button>
	);
}

// apps/playground/src/samples/Button.sample.vue
<script setup lang="ts">
import { button } from "./styleframe.config";

const props = withDefaults(
	defineProps<{
		color?:
			| "primary"
			| "secondary"
			| "success"
			| "info"
			| "warning"
			| "error"
			| "light"
			| "dark"
			| "neutral";
		variant?: "solid" | "outline" | "soft" | "subtle" | "ghost" | "link";
		size?: "xs" | "sm" | "md" | "lg" | "xl";
		label?: string;
		disabled?: boolean;
	}>(),
	{
		color: "primary",
		variant: "solid",
		size: "md",
	},
);
</script>

<template>
	<button
		type="button"
		:class="
			button({ color: props.color, variant: props.variant, size: props.size })
		"
		:disabled="props.disabled"
	>
		<slot>{{ props.label }}</slot>
	</button>
</template>
