// apps/playground/src/samples/Card.sample.tsx
import type { ReactNode } from "react";
import { card, cardBody, cardFooter, cardHeader } from "virtual:styleframe";

interface CardProps {
	color?: "light" | "dark" | "neutral";
	variant?: "solid" | "soft" | "subtle";
	size?: "sm" | "md" | "lg";
	header?: ReactNode;
	footer?: ReactNode;
	children?: ReactNode;
}

export default function Card({
	color = "light",
	variant = "solid",
	size = "md",
	header,
	footer,
	children,
}: CardProps) {
	return (
		<article className={card({ color, variant, size })}>
			{header ? <header className={cardHeader()}>{header}</header> : null}
			<div className={cardBody()}>{children}</div>
			{footer ? <footer className={cardFooter()}>{footer}</footer> : null}
		</article>
	);
}

// apps/playground/src/samples/Card.sample.vue
<script setup lang="ts">
import { card, cardBody, cardFooter, cardHeader } from "./styleframe.config";

const props = withDefaults(
	defineProps<{
		color?: "light" | "dark" | "neutral";
		variant?: "solid" | "soft" | "subtle";
		size?: "sm" | "md" | "lg";
	}>(),
	{
		color: "light",
		variant: "solid",
		size: "md",
	},
);
</script>

<template>
	<article :class="card({ color: props.color, variant: props.variant, size: props.size })">
		<header :class="cardHeader()">
			<slot name="header" />
		</header>
		<div :class="cardBody()">
			<slot />
		</div>
		<footer :class="cardFooter()">
			<slot name="footer" />
		</footer>
	</article>
</template>
